//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Windows;

	public class App : Application
	{
		public virtual object language
		{
			get;
			set;
		}

		public virtual object lastUsedProjects
		{
			get;
			set;
		}

		public virtual Caretaker : Collection<Memento> Caretaker
		{
			get;
			set;
		}

		public virtual void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		public static void Main()
		{
			throw new System.NotImplementedException();
		}

		public App()
		{
		}

	}
}

