//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MainWindow
	{
		public virtual Treeview ProjectExplorer
		{
			get;
			set;
		}

		private void decoratePluginList(object OptType type)
		{
			throw new System.NotImplementedException();
		}

		private void initPluginOptions()
		{
			throw new System.NotImplementedException();
		}

		private void initSmartTree()
		{
			throw new System.NotImplementedException();
		}

		private void initFileExplorer()
		{
			throw new System.NotImplementedException();
		}

	}
}

