//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using Model;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    using OqatPublicRessources.Model;
    using OqatPublicRessources.Plugin;
    using System.IO;

	public class PluginManager
	{
		private PluginManager pluginManager
		{
			get;
			set;
		}

		private Dictionary<PluginType,Dictionary<string, IPlugin>> pluginTable
		{
			get;
			set;
		}

		private Caretaker caretaker
		{
			get;
			set;
		}

		private Path pluginPath
		{
			get;
			set;
		}

        public delegate void eventHandler(object sender, EventArgs e);

		private Dictionary<EventType, List<event eventHandler as>> eventTable
		{
			get;
			set;
		}

		public virtual void loadPluginTable()
		{
			throw new System.NotImplementedException();
		}

		public virtual void getPluginManager()
		{
			throw new System.NotImplementedException();
		}

		private PluginManager()
		{
		}

		public virtual Memento getMemento(object string namePlugin, object string nameMemento)
		{
			throw new System.NotImplementedException();
		}

		public virtual IPlugin getPlugin(object string namePlugin)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<string> getPluginNames(object PluginType type)
		{
			throw new System.NotImplementedException();
		}

		public virtual void addEvent(object EventType eType, object event e)
		{
			throw new System.NotImplementedException();
		}

		public virtual void addEventHandler(object EventType eType, object del handler)
		{
			throw new System.NotImplementedException();
		}

		public virtual void rmEventHandler(object EventType eType, object del handler)
		{
			throw new System.NotImplementedException();
		}

		public virtual void rmEvent(object EventType eType, object event e)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<String> getMementoNames(object string namePlugin)
		{
			throw new System.NotImplementedException();
		}

	}
}

