//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_Menu
	{
		private object menuItem_Project
		{
			get;
			set;
		}

		private object menuItem_Properties
		{
			get;
			set;
		}

		private object vM_optionsDialog
		{
			get;
			set;
		}

		private object vM_ProjectOpenDialog
		{
			get;
			set;
		}

		public VM_Menu(object Control parent, object del onBuildProjectView)
		{
		}

	}
}

