//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_OptionsDialog
	{
		public virtual TreeView optionsTree
		{
			get;
			set;
		}

		private event buildProjectView
		{
			get;
			set;
		}

		public virtual void VM_Menu()
		{
			throw new System.NotImplementedException();
		}

	}
}

