//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using AForge.Controls;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_Presentation
	{
		private ViewType currentView
		{
			get;
			set;
		}

		private event flushPresentationPlugins
		{
			get;
			set;
		}

		public virtual IEnumerable<VideoSourcePlayer> VideoSourcePlayer
		{
			get;
			set;
		}

		private void onVideoLoad(object Object sender, object VideoEventArgs e))
		{
			throw new System.NotImplementedException();
		}

		private void onToggleView(object object sender, object ViewTypeEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public VM_Presentation()
		{
		}

		private void resetPanel()
		{
			throw new System.NotImplementedException();
		}

	}
}

