//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>
	/// zu welcher view Tatsächlich getoggelt  wird hängt davon ab was im argument des events übergeben wird (Filter, Metrik, AnalyseErgebniss)
	/// 
	/// Dieses ereignis sollte von Presentation abgefangen werden
	/// </remarks>
	public class VM_PluginLists
	{
		private object PluginLists
		{
			get;
			set;
		}

		private object filterList
		{
			get;
			set;
		}

		private object metricList
		{
			get;
			set;
		}

		private Button delete
		{
			get;
			set;
		}

		private object pluginManager
		{
			get;
			set;
		}

		private Caretaker caretaker
		{
			get;
			set;
		}

		private event toggleView
		{
			get;
			set;
		}

		private event entrySelect
		{
			get;
			set;
		}

		private del onNewMementoCreated(Object sender, EventArgs e)
		{
			get;
			set;
		}

		private event entryClick
		{
			get;
			set;
		}

		private delegate onMacroFilterEntrySelected(Object sender, EventArgs e)
		{
			get;
			set;
		}

		public VM_PluginLists(object Control parent)
		{
		}

		private void onMacroFilterEntryClicked(object object sender, object MementoEventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

