//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_Welcome
	{
		public virtual object lastUsedProjects
		{
			get;
			set;
		}

		public virtual Caretaker caretaker
		{
			get;
			set;
		}

		public virtual string name
		{
			get;
			set;
		}

		public virtual event selectProject
		{
			get;
			set;
		}

		public VM_Welcome(object Control parent)
		{
		}

	}
}

