//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace System
{
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class EventArgs
	{
		public static EventArgs Empty;

		public EventArgs()
		{
		}

	}
}

