//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to register application for restart due to bad parameters. ähnelt.
        /// </summary>
        internal static string ApplicationRecoverFailedToRegisterForRestartBadParameters {
            get {
                return ResourceManager.GetString("ApplicationRecoverFailedToRegisterForRestartBadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application was not registered for recovery due to bad parameters. ähnelt.
        /// </summary>
        internal static string ApplicationRecoveryBadParameters {
            get {
                return ResourceManager.GetString("ApplicationRecoveryBadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application failed to register for recovery. ähnelt.
        /// </summary>
        internal static string ApplicationRecoveryFailedToRegister {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application failed to registered for restart. ähnelt.
        /// </summary>
        internal static string ApplicationRecoveryFailedToRegisterForRestart {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToRegisterForRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unregister for recovery failed. ähnelt.
        /// </summary>
        internal static string ApplicationRecoveryFailedToUnregister {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unregister for restart failed. ähnelt.
        /// </summary>
        internal static string ApplicationRecoveryFailedToUnregisterForRestart {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToUnregisterForRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This method must be called from the registered callback method. ähnelt.
        /// </summary>
        internal static string ApplicationRecoveryMustBeCalledFromCallback {
            get {
                return ResourceManager.GetString("ApplicationRecoveryMustBeCalledFromCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ACOnline: {1}{0}Max Charge: {2} mWh{0}Current Charge: {3} mWh{0}Discharge Rate: {4} mWh{0}Estimated Time Remaining: {5}{0}Suggested Critical Battery Charge: {6} mWh{0}Suggested Battery Warning Charge: {7} mWh{0} ähnelt.
        /// </summary>
        internal static string BatteryStateStringRepresentation {
            get {
                return ResourceManager.GetString("BatteryStateStringRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancelable cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string CancelableCannotBeChanged {
            get {
                return ResourceManager.GetString("CancelableCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog caption cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string CaptionCannotBeChanged {
            get {
                return ResourceManager.GetString("CaptionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckBox text cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string CheckBoxCannotBeChanged {
            get {
                return ResourceManager.GetString("CheckBoxCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collapsed control text cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string CollapsedTextCannotBeChanged {
            get {
                return ResourceManager.GetString("CollapsedTextCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only supported on Windows 7 or newer. ähnelt.
        /// </summary>
        internal static string CoreHelpersRunningOn7 {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only supported on Windows Vista or newer. ähnelt.
        /// </summary>
        internal static string CoreHelpersRunningOnVista {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOnVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only supported on Windows XP or newer. ähnelt.
        /// </summary>
        internal static string CoreHelpersRunningOnXp {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOnXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog cannot have more than one control with the same name. ähnelt.
        /// </summary>
        internal static string DialogCollectionCannotHaveDuplicateNames {
            get {
                return ResourceManager.GetString("DialogCollectionCannotHaveDuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog control must be removed from current collections first. ähnelt.
        /// </summary>
        internal static string DialogCollectionControlAlreadyHosted {
            get {
                return ResourceManager.GetString("DialogCollectionControlAlreadyHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control name cannot be null or zero length. ähnelt.
        /// </summary>
        internal static string DialogCollectionControlNameNull {
            get {
                return ResourceManager.GetString("DialogCollectionControlNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modifying controls collection while dialog is showing is not supported. ähnelt.
        /// </summary>
        internal static string DialogCollectionModifyShowingDialog {
            get {
                return ResourceManager.GetString("DialogCollectionModifyShowingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog control name cannot be empty or null. ähnelt.
        /// </summary>
        internal static string DialogControlNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("DialogControlNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog controls cannot be renamed. ähnelt.
        /// </summary>
        internal static string DialogControlsCannotBeRenamed {
            get {
                return ResourceManager.GetString("DialogControlsCannotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        internal static string DialogDefaultCaption {
            get {
                return ResourceManager.GetString("DialogDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DialogDefaultContent {
            get {
                return ResourceManager.GetString("DialogDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DialogDefaultMainInstruction {
            get {
                return ResourceManager.GetString("DialogDefaultMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expanded information mode cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string ExpandedDetailsCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandedDetailsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expanded control label cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string ExpandedLabelCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandedLabelCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expanding state of the dialog cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string ExpandingStateCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandingStateCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hyperlinks cannot be enabled/disabled while dialog is showing. ähnelt.
        /// </summary>
        internal static string HyperlinksCannotBetSet {
            get {
                return ResourceManager.GetString("HyperlinksCannotBetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference path is invalid. ähnelt.
        /// </summary>
        internal static string InvalidReferencePath {
            get {
                return ResourceManager.GetString("InvalidReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified event handler has not been registered. ähnelt.
        /// </summary>
        internal static string MessageManagerHandlerNotRegistered {
            get {
                return ResourceManager.GetString("MessageManagerHandlerNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occurred in dialog configuration. ähnelt.
        /// </summary>
        internal static string NativeTaskDialogConfigurationError {
            get {
                return ResourceManager.GetString("NativeTaskDialogConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid arguments to Win32 call. ähnelt.
        /// </summary>
        internal static string NativeTaskDialogInternalErrorArgs {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog contents too complex. ähnelt.
        /// </summary>
        internal static string NativeTaskDialogInternalErrorComplex {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected internal error occurred in the Win32 call: {0:x} ähnelt.
        /// </summary>
        internal static string NativeTaskDialogInternalErrorUnexpected {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TaskDialog feature needs to load version 6 of comctl32.dll but a different version is current loaded in memory. ähnelt.
        /// </summary>
        internal static string NativeTaskDialogVersionError {
            get {
                return ResourceManager.GetString("NativeTaskDialogVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog owner cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string OwnerCannotBeChanged {
            get {
                return ResourceManager.GetString("OwnerCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SetThreadExecutionState call failed. ähnelt.
        /// </summary>
        internal static string PowerExecutionStateFailed {
            get {
                return ResourceManager.GetString("PowerExecutionStateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The caller had insufficient access rights to get the system battery state. ähnelt.
        /// </summary>
        internal static string PowerInsufficientAccessBatteryState {
            get {
                return ResourceManager.GetString("PowerInsufficientAccessBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The caller had insufficient access rights to get the system power capabilities. ähnelt.
        /// </summary>
        internal static string PowerInsufficientAccessCapabilities {
            get {
                return ResourceManager.GetString("PowerInsufficientAccessCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to get active power scheme. ähnelt.
        /// </summary>
        internal static string PowerManagerActiveSchemeFailed {
            get {
                return ResourceManager.GetString("PowerManagerActiveSchemeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery is not present on this system. ähnelt.
        /// </summary>
        internal static string PowerManagerBatteryNotPresent {
            get {
                return ResourceManager.GetString("PowerManagerBatteryNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress bar cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string ProgressBarCannotBeChanged {
            get {
                return ResourceManager.GetString("ProgressBarCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress bar cannot be hosted in multiple dialogs. ähnelt.
        /// </summary>
        internal static string ProgressBarCannotBeHostedInMultipleDialogs {
            get {
                return ResourceManager.GetString("ProgressBarCannotBeHostedInMultipleDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}, {1} ähnelt.
        /// </summary>
        internal static string PropertyKeyFormatString {
            get {
                return ResourceManager.GetString("PropertyKeyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to initialize PropVariant. ähnelt.
        /// </summary>
        internal static string PropVariantInitializationError {
            get {
                return ResourceManager.GetString("PropVariantInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi-dimensional SafeArrays not supported. ähnelt.
        /// </summary>
        internal static string PropVariantMultiDimArray {
            get {
                return ResourceManager.GetString("PropVariantMultiDimArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String argument cannot be null or empty. ähnelt.
        /// </summary>
        internal static string PropVariantNullString {
            get {
                return ResourceManager.GetString("PropVariantNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Value type is not supported. ähnelt.
        /// </summary>
        internal static string PropVariantTypeNotSupported {
            get {
                return ResourceManager.GetString("PropVariantTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot be cast to unsupported type. ähnelt.
        /// </summary>
        internal static string PropVariantUnsupportedType {
            get {
                return ResourceManager.GetString("PropVariantUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delegate: {0}, state: {1}, ping: {2} ähnelt.
        /// </summary>
        internal static string RecoverySettingsFormatString {
            get {
                return ResourceManager.GetString("RecoverySettingsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die command: {0} restrictions: {1} ähnelt.
        /// </summary>
        internal static string RestartSettingsFormatString {
            get {
                return ResourceManager.GetString("RestartSettingsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StandardButtons cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string StandardButtonsCannotBeChanged {
            get {
                return ResourceManager.GetString("StandardButtonsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startup location cannot be changed while dialog is showing. ähnelt.
        /// </summary>
        internal static string StartupLocationCannotBeChanged {
            get {
                return ResourceManager.GetString("StartupLocationCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bad button ID in closing event. ähnelt.
        /// </summary>
        internal static string TaskDialogBadButtonId {
            get {
                return ResourceManager.GetString("TaskDialogBadButtonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button text must be non-empty. ähnelt.
        /// </summary>
        internal static string TaskDialogButtonTextEmpty {
            get {
                return ResourceManager.GetString("TaskDialogButtonTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check box text must be provided to enable the dialog check box. ähnelt.
        /// </summary>
        internal static string TaskDialogCheckBoxTextRequiredToEnableCheckBox {
            get {
                return ResourceManager.GetString("TaskDialogCheckBoxTextRequiredToEnableCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attempting to close a non-showing dialog. ähnelt.
        /// </summary>
        internal static string TaskDialogCloseNonShowing {
            get {
                return ResourceManager.GetString("TaskDialogCloseNonShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        internal static string TaskDialogDefaultCaption {
            get {
                return ResourceManager.GetString("TaskDialogDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string TaskDialogDefaultContent {
            get {
                return ResourceManager.GetString("TaskDialogDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string TaskDialogDefaultMainInstruction {
            get {
                return ResourceManager.GetString("TaskDialogDefaultMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot have more than one default button of a given type. ähnelt.
        /// </summary>
        internal static string TaskDialogOnlyOneDefaultControl {
            get {
                return ResourceManager.GetString("TaskDialogOnlyOneDefaultControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum value provided must be greater than the minimum value. ähnelt.
        /// </summary>
        internal static string TaskDialogProgressBarMaxValueGreaterThanMin {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMaxValueGreaterThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum value provided must be a positive number. ähnelt.
        /// </summary>
        internal static string TaskDialogProgressBarMinValueGreaterThanZero {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMinValueGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum value provided must less than the maximum value. ähnelt.
        /// </summary>
        internal static string TaskDialogProgressBarMinValueLessThanMax {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMinValueLessThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value provided must be greater than equal to the minimum value and less than the maximum value. ähnelt.
        /// </summary>
        internal static string TaskDialogProgressBarValueInRange {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarValueInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog cannot display both non-standard buttons and standard buttons. ähnelt.
        /// </summary>
        internal static string TaskDialogSupportedButtonsAndButtons {
            get {
                return ResourceManager.GetString("TaskDialogSupportedButtonsAndButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog cannot display both non-standard buttons and command links. ähnelt.
        /// </summary>
        internal static string TaskDialogSupportedButtonsAndLinks {
            get {
                return ResourceManager.GetString("TaskDialogSupportedButtonsAndLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown dialog control type. ähnelt.
        /// </summary>
        internal static string TaskDialogUnkownControl {
            get {
                return ResourceManager.GetString("TaskDialogUnkownControl", resourceCulture);
            }
        }
    }
}
