//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Memento
	{
		public virtual string namePlugin
		{
			get;
			set;
		}

		public virtual string nameMemento
		{
			get;
			set;
		}

		public virtual Object state
		{
			get;
			set;
		}

		public virtual IStorable IStorable
		{
			get;
			set;
		}

		public Memento(object IDOrigin idOrigin, object String name, object Object state)
		{
		}

	}
}

