//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using OqatInterface;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Project : IMemorizable
	{
		private name string
		{
			get;
			set;
		}

		private description string
		{
			get;
			set;
		}

		private Path path_Project
		{
			get;
			set;
		}

		public virtual SmartNode<T> : where T: SmartNode SmartTree
		{
			get;
			set;
		}

		public Project(object string name, object Path path, object List<Video> vidList, object string description)
		{
		}

		public Project(object Path path)
		{
		}

		public Project(object string name, object Path path, object string description)
		{
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

	}
}

