//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Project : IPresentation
	{
		private name string
		{
			get;
			set;
		}

		private description string
		{
			get;
			set;
		}

		public virtual object Analysevorgaenge
		{
			get;
			set;
		}

		public virtual object Projekteinstellungen
		{
			get;
			set;
		}

		public virtual SmartNode Resources
		{
			get;
			set;
		}

		public virtual void getOptionsView()
		{
			throw new System.NotImplementedException();
		}

		public virtual int getProgress()
		{
			throw new System.NotImplementedException();
		}

	}
}

