//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SmartNode : List<SmartNode>
	{
		public virtual string name
		{
			get;
			set;
		}

		public virtual string filteredBy
		{
			get;
			set;
		}

		public virtual Path filepath
		{
			get;
			set;
		}

		public virtual bool isAnalysis
		{
			get;
			set;
		}

		public virtual IEnumerable<SmartNode> Child
		{
			get;
			set;
		}

		public virtual Video Video
		{
			get;
			set;
		}

	}
}

