//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using Aforge;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Video : IVideoSource
	{
		private int width
		{
			get;
			set;
		}

		private int height
		{
			get;
			set;
		}

		private Path path
		{
			get;
			set;
		}

		public virtual IEnumerable<Bitmap> Frame
		{
			get;
			set;
		}

		public virtual void + Video(object String file, object int height, object int width)
		{
			throw new System.NotImplementedException();
		}

	}
}

