//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using OqatInterface;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Video : IMemorizable
	{
		private IVideoInfo vidInfo
		{
			get;
			set;
		}

		private bool isAnalysis
		{
			get;
			set;
		}

		private Path vidPath
		{
			get;
			set;
		}

		private float [] frameMetricValue
		{
			get;
			set;
		}

		private List<MacroEntrys> filteredBy
		{
			get;
			set;
		}

		private Path extraRessource
		{
			get;
			set;
		}

		public Video(object bool isAnalysis, object Path vidPath, object IVideoInfo vidInfo)
		{
		}

		public virtual IVideoHandler getVideoHandler()
		{
			throw new System.NotImplementedException();
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

	}
}

