//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.Metric
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IMetric  : IMemorizable
	{
		void getAnalysisView();

		void analyse(object Video ref, object Video proc);

	}
}

