//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.Metric
{
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PM_MSE : IPlugin, IMetric
	{
		public virtual void getOptionsView()
		{
			throw new System.NotImplementedException();
		}

		public virtual void getAnalysisView()
		{
			throw new System.NotImplementedException();
		}

		public virtual void analyse(object Video ref, object Video proc)
		{
			throw new System.NotImplementedException();
		}

		public virtual int getProgress()
		{
			throw new System.NotImplementedException();
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

	}
}

