// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom codierten UI-Testbuilder generiert.
//      Version: 10.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      codierten UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OQAT_Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// projectcreate - Verwenden Sie "projectcreateParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void projectcreate()
        {
            #region Variable Declarations
            WpfButton uINeuesProjekterstelleButton = this.UIObjectiveQualityAsseWindow.UIItemCustom.UINeuesProjekterstelleButton;
            WpfButton uIBrowseButton = this.UINeuesProjekterstelleWindow.UITitelundPfadwählenGroup.UIBrowseButton;
            WinComboBox uIDateinameComboBox = this.UISpeichernunterWindow.UIDetailbereichPane.UIDateinameComboBox;
            WinButton uISpeichernButton = this.UISpeichernunterWindow.UISpeichernWindow.UISpeichernButton;
            WpfEdit uIProjDescFieldEdit = this.UINeuesProjekterstelleWindow.UIBeschreibungGroup.UIProjDescFieldEdit;
            WpfEdit uIItemEdit = this.UINeuesProjekterstelleWindow.UITitelundPfadwählenGroup.UITitelText.UIItemEdit;
            WpfButton uIProjekterstellenButton = this.UINeuesProjekterstelleWindow.UIProjekterstellenButton;
            #endregion

            // "%USERPROFILE%\MMWTV\Implementierung\OQAT\bin\Debug\OQAT.exe" starten
            ApplicationUnderTest uIObjectiveQualityAsseWindow = ApplicationUnderTest.Launch(this.projectcreateParams.UIObjectiveQualityAsseWindowExePath, this.projectcreateParams.UIObjectiveQualityAsseWindowAlternateExePath);

            // Klicken "Neues Projekt erstellen" Schaltfläche
            Mouse.Click(uINeuesProjekterstelleButton, new Point(131, 19));

            // Klicken "Browse" Schaltfläche
            Mouse.Click(uIBrowseButton, new Point(121, 35));

            // "test.oqatPrj" in "Dateiname:" Kombinationsfeld auswählen
            uIDateinameComboBox.EditableItem = this.projectcreateParams.UIDateinameComboBoxEditableItem;

            // Klicken "&Speichern" Schaltfläche
            Mouse.Click(uISpeichernButton, new Point(37, 23));

            // "Hallo" in "projDescField" Textfeld eingeben
            uIProjDescFieldEdit.Text = this.projectcreateParams.UIProjDescFieldEditText;

            // "testen" in erstes Textfeld neben "Titel:" Beschriftung eingeben
            uIItemEdit.Text = this.projectcreateParams.UIItemEditText;

            // Klicken "Projekt erstellen" Schaltfläche
            Mouse.Click(uIProjekterstellenButton, new Point(295, 23));
        }
        
        /// <summary>
        /// Cancelbutton - Verwenden Sie "CancelbuttonParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void Cancelbutton()
        {
            #region Variable Declarations
            WpfButton uIProjektsuchenButton = this.UIObjectiveQualityAsseWindow.UIItemCustom.UIProjektsuchenButton;
            WinButton uISchließenButton = this.UIÖffnenWindow.UIÖffnenTitleBar.UISchließenButton;
            WpfButton uINeuesProjekterstelleButton = this.UIObjectiveQualityAsseWindow.UIItemCustom.UINeuesProjekterstelleButton;
            WpfButton uIAbbrechenButton = this.UINeuesProjekterstelleWindow.UIAbbrechenButton;
            #endregion

            // "%USERPROFILE%\MMWTV\Implementierung\OQAT\bin\Debug\OQAT.exe" starten
            ApplicationUnderTest uIObjectiveQualityAsseWindow = ApplicationUnderTest.Launch(this.CancelbuttonParams.UIObjectiveQualityAsseWindowExePath, this.CancelbuttonParams.UIObjectiveQualityAsseWindowAlternateExePath);

            // Klicken "Projekt suchen" Schaltfläche
            Mouse.Click(uIProjektsuchenButton, new Point(54, 6));

            // Klicken "Schließen" Schaltfläche
            Mouse.Click(uISchließenButton, new Point(27, 3));

            // Klicken "Neues Projekt erstellen" Schaltfläche
            Mouse.Click(uINeuesProjekterstelleButton, new Point(112, 20));

            // Klicken "Abbrechen" Schaltfläche
            Mouse.Click(uIAbbrechenButton, new Point(324, 15));
        }
        
        /// <summary>
        /// Assertsuccesfullproject - Verwenden Sie "AssertsuccesfullprojectExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void Assertsuccesfullproject()
        {
            #region Variable Declarations
            WinListItem uIOttooqatPrjListItem = this.UIProgramManagerWindow.UIDesktopList.UIOttooqatPrjListItem;
            #endregion

            // Überprüfen, ob Eigenschaft von "otto.oqatPrj"-Listenelement Exists True entspricht
            Assert.AreEqual(this.AssertsuccesfullprojectExpectedValues.UIOttooqatPrjListItemExists, uIOttooqatPrjListItem.Exists);

            // Überprüfen, ob Eigenschaft von "otto.oqatPrj"-Listenelement DisplayText otto.oqatPrj entspricht
            Assert.AreEqual(this.AssertsuccesfullprojectExpectedValues.UIOttooqatPrjListItemDisplayText, uIOttooqatPrjListItem.DisplayText);
        }
        
        /// <summary>
        /// AssertMethod1 - Verwenden Sie "AssertMethod1ExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            WinListItem uITestoqatPrjListItem = this.UIProgramManagerWindow.UIDesktopList.UITestoqatPrjListItem;
            #endregion

            // Überprüfen, ob Eigenschaft von "test.oqatPrj"-Listenelement Exists True entspricht
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UITestoqatPrjListItemExists, uITestoqatPrjListItem.Exists);
        }
        
        /// <summary>
        /// AssertMethod2 - Verwenden Sie "AssertMethod2ExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertMethod2()
        {
            #region Variable Declarations
            WinListItem uITestoqatPrjListItem = this.UIProgramManagerWindow.UIDesktopList.UITestoqatPrjListItem;
            #endregion

            // Überprüfen, ob Eigenschaft von "test.oqatPrj"-Listenelement DisplayText test.oqatPrj entspricht
            Assert.AreEqual(this.AssertMethod2ExpectedValues.UITestoqatPrjListItemDisplayText, uITestoqatPrjListItem.DisplayText);
        }
        
        #region Properties
        public virtual projectcreateParams projectcreateParams
        {
            get
            {
                if ((this.mprojectcreateParams == null))
                {
                    this.mprojectcreateParams = new projectcreateParams();
                }
                return this.mprojectcreateParams;
            }
        }
        
        public virtual CancelbuttonParams CancelbuttonParams
        {
            get
            {
                if ((this.mCancelbuttonParams == null))
                {
                    this.mCancelbuttonParams = new CancelbuttonParams();
                }
                return this.mCancelbuttonParams;
            }
        }
        
        public virtual AssertsuccesfullprojectExpectedValues AssertsuccesfullprojectExpectedValues
        {
            get
            {
                if ((this.mAssertsuccesfullprojectExpectedValues == null))
                {
                    this.mAssertsuccesfullprojectExpectedValues = new AssertsuccesfullprojectExpectedValues();
                }
                return this.mAssertsuccesfullprojectExpectedValues;
            }
        }
        
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual AssertMethod2ExpectedValues AssertMethod2ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod2ExpectedValues == null))
                {
                    this.mAssertMethod2ExpectedValues = new AssertMethod2ExpectedValues();
                }
                return this.mAssertMethod2ExpectedValues;
            }
        }
        
        public UIObjectiveQualityAsseWindow UIObjectiveQualityAsseWindow
        {
            get
            {
                if ((this.mUIObjectiveQualityAsseWindow == null))
                {
                    this.mUIObjectiveQualityAsseWindow = new UIObjectiveQualityAsseWindow();
                }
                return this.mUIObjectiveQualityAsseWindow;
            }
        }
        
        public UINeuesProjekterstelleWindow UINeuesProjekterstelleWindow
        {
            get
            {
                if ((this.mUINeuesProjekterstelleWindow == null))
                {
                    this.mUINeuesProjekterstelleWindow = new UINeuesProjekterstelleWindow();
                }
                return this.mUINeuesProjekterstelleWindow;
            }
        }
        
        public UISpeichernunterWindow UISpeichernunterWindow
        {
            get
            {
                if ((this.mUISpeichernunterWindow == null))
                {
                    this.mUISpeichernunterWindow = new UISpeichernunterWindow();
                }
                return this.mUISpeichernunterWindow;
            }
        }
        
        public UIÖffnenWindow UIÖffnenWindow
        {
            get
            {
                if ((this.mUIÖffnenWindow == null))
                {
                    this.mUIÖffnenWindow = new UIÖffnenWindow();
                }
                return this.mUIÖffnenWindow;
            }
        }
        
        public UIProgramManagerWindow UIProgramManagerWindow
        {
            get
            {
                if ((this.mUIProgramManagerWindow == null))
                {
                    this.mUIProgramManagerWindow = new UIProgramManagerWindow();
                }
                return this.mUIProgramManagerWindow;
            }
        }
        #endregion
        
        #region Fields
        private projectcreateParams mprojectcreateParams;
        
        private CancelbuttonParams mCancelbuttonParams;
        
        private AssertsuccesfullprojectExpectedValues mAssertsuccesfullprojectExpectedValues;
        
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private AssertMethod2ExpectedValues mAssertMethod2ExpectedValues;
        
        private UIObjectiveQualityAsseWindow mUIObjectiveQualityAsseWindow;
        
        private UINeuesProjekterstelleWindow mUINeuesProjekterstelleWindow;
        
        private UISpeichernunterWindow mUISpeichernunterWindow;
        
        private UIÖffnenWindow mUIÖffnenWindow;
        
        private UIProgramManagerWindow mUIProgramManagerWindow;
        #endregion
    }
    
    /// <summary>
    /// An "projectcreate" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class projectcreateParams
    {
        
        #region Fields
        /// <summary>
        /// "%USERPROFILE%\MMWTV\Implementierung\OQAT\bin\Debug\OQAT.exe" starten
        /// </summary>
        public string UIObjectiveQualityAsseWindowExePath = "C:\\Users\\GRILLEDSHEEP\\MMWTV\\Implementierung\\OQAT\\bin\\Debug\\OQAT.exe";
        
        /// <summary>
        /// "%USERPROFILE%\MMWTV\Implementierung\OQAT\bin\Debug\OQAT.exe" starten
        /// </summary>
        public string UIObjectiveQualityAsseWindowAlternateExePath = "%USERPROFILE%\\MMWTV\\Implementierung\\OQAT\\bin\\Debug\\OQAT.exe";
        
        /// <summary>
        /// "test.oqatPrj" in "Dateiname:" Kombinationsfeld auswählen
        /// </summary>
        public string UIDateinameComboBoxEditableItem = "test.oqatPrj";
        
        /// <summary>
        /// "Hallo" in "projDescField" Textfeld eingeben
        /// </summary>
        public string UIProjDescFieldEditText = "Hallo";
        
        /// <summary>
        /// "testen" in erstes Textfeld neben "Titel:" Beschriftung eingeben
        /// </summary>
        public string UIItemEditText = "testen";
        #endregion
    }
    
    /// <summary>
    /// An "Cancelbutton" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class CancelbuttonParams
    {
        
        #region Fields
        /// <summary>
        /// "%USERPROFILE%\MMWTV\Implementierung\OQAT\bin\Debug\OQAT.exe" starten
        /// </summary>
        public string UIObjectiveQualityAsseWindowExePath = "C:\\Users\\GRILLEDSHEEP\\MMWTV\\Implementierung\\OQAT\\bin\\Debug\\OQAT.exe";
        
        /// <summary>
        /// "%USERPROFILE%\MMWTV\Implementierung\OQAT\bin\Debug\OQAT.exe" starten
        /// </summary>
        public string UIObjectiveQualityAsseWindowAlternateExePath = "%USERPROFILE%\\MMWTV\\Implementierung\\OQAT\\bin\\Debug\\OQAT.exe";
        #endregion
    }
    
    /// <summary>
    /// An "Assertsuccesfullproject" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class AssertsuccesfullprojectExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Überprüfen, ob Eigenschaft von "otto.oqatPrj"-Listenelement Exists True entspricht
        /// </summary>
        public bool UIOttooqatPrjListItemExists = true;
        
        /// <summary>
        /// Überprüfen, ob Eigenschaft von "otto.oqatPrj"-Listenelement DisplayText otto.oqatPrj entspricht
        /// </summary>
        public string UIOttooqatPrjListItemDisplayText = "otto.oqatPrj";
        #endregion
    }
    
    /// <summary>
    /// An "AssertMethod1" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Überprüfen, ob Eigenschaft von "test.oqatPrj"-Listenelement Exists True entspricht
        /// </summary>
        public bool UITestoqatPrjListItemExists = true;
        #endregion
    }
    
    /// <summary>
    /// An "AssertMethod2" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class AssertMethod2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Überprüfen, ob Eigenschaft von "test.oqatPrj"-Listenelement DisplayText test.oqatPrj entspricht
        /// </summary>
        public string UITestoqatPrjListItemDisplayText = "test.oqatPrj";
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIObjectiveQualityAsseWindow : WpfWindow
    {
        
        public UIObjectiveQualityAsseWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Objective Quality Assessment Toolkit";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Objective Quality Assessment Toolkit");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.VM_Welcome";
            this.WindowTitles.Add("Objective Quality Assessment Toolkit");
            #endregion
        }
        
        #region Properties
        public WpfButton UINeuesProjekterstelleButton
        {
            get
            {
                if ((this.mUINeuesProjekterstelleButton == null))
                {
                    this.mUINeuesProjekterstelleButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUINeuesProjekterstelleButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "newPrjCreate_Button";
                    this.mUINeuesProjekterstelleButton.WindowTitles.Add("Objective Quality Assessment Toolkit");
                    #endregion
                }
                return this.mUINeuesProjekterstelleButton;
            }
        }
        
        public WpfButton UIProjektsuchenButton
        {
            get
            {
                if ((this.mUIProjektsuchenButton == null))
                {
                    this.mUIProjektsuchenButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIProjektsuchenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnEx";
                    this.mUIProjektsuchenButton.WindowTitles.Add("Objective Quality Assessment Toolkit");
                    #endregion
                }
                return this.mUIProjektsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUINeuesProjekterstelleButton;
        
        private WpfButton mUIProjektsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UINeuesProjekterstelleWindow : WpfWindow
    {
        
        public UINeuesProjekterstelleWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Neues Projekt erstellen.";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Neues Projekt erstellen.");
            #endregion
        }
        
        #region Properties
        public UITitelundPfadwählenGroup UITitelundPfadwählenGroup
        {
            get
            {
                if ((this.mUITitelundPfadwählenGroup == null))
                {
                    this.mUITitelundPfadwählenGroup = new UITitelundPfadwählenGroup(this);
                }
                return this.mUITitelundPfadwählenGroup;
            }
        }
        
        public UIBeschreibungGroup UIBeschreibungGroup
        {
            get
            {
                if ((this.mUIBeschreibungGroup == null))
                {
                    this.mUIBeschreibungGroup = new UIBeschreibungGroup(this);
                }
                return this.mUIBeschreibungGroup;
            }
        }
        
        public WpfButton UIProjekterstellenButton
        {
            get
            {
                if ((this.mUIProjekterstellenButton == null))
                {
                    this.mUIProjekterstellenButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIProjekterstellenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "bt1";
                    this.mUIProjekterstellenButton.WindowTitles.Add("Neues Projekt erstellen.");
                    #endregion
                }
                return this.mUIProjekterstellenButton;
            }
        }
        
        public WpfButton UIAbbrechenButton
        {
            get
            {
                if ((this.mUIAbbrechenButton == null))
                {
                    this.mUIAbbrechenButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIAbbrechenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "bt2";
                    this.mUIAbbrechenButton.WindowTitles.Add("Neues Projekt erstellen.");
                    #endregion
                }
                return this.mUIAbbrechenButton;
            }
        }
        #endregion
        
        #region Fields
        private UITitelundPfadwählenGroup mUITitelundPfadwählenGroup;
        
        private UIBeschreibungGroup mUIBeschreibungGroup;
        
        private WpfButton mUIProjekterstellenButton;
        
        private WpfButton mUIAbbrechenButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UITitelundPfadwählenGroup : WpfGroup
    {
        
        public UITitelundPfadwählenGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfGroup.PropertyNames.AutomationId] = "gb3";
            this.WindowTitles.Add("Neues Projekt erstellen.");
            #endregion
        }
        
        #region Properties
        public WpfButton UIBrowseButton
        {
            get
            {
                if ((this.mUIBrowseButton == null))
                {
                    this.mUIBrowseButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIBrowseButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnBrowse";
                    this.mUIBrowseButton.WindowTitles.Add("Neues Projekt erstellen.");
                    #endregion
                }
                return this.mUIBrowseButton;
            }
        }
        
        public UITitelText UITitelText
        {
            get
            {
                if ((this.mUITitelText == null))
                {
                    this.mUITitelText = new UITitelText(this);
                }
                return this.mUITitelText;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIBrowseButton;
        
        private UITitelText mUITitelText;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UITitelText : WpfText
    {
        
        public UITitelText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfText.PropertyNames.AutomationId] = "tb5";
            this.WindowTitles.Add("Neues Projekt erstellen.");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Suchkriterien
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("Neues Projekt erstellen.");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIBeschreibungGroup : WpfGroup
    {
        
        public UIBeschreibungGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfGroup.PropertyNames.AutomationId] = "gb4";
            this.WindowTitles.Add("Neues Projekt erstellen.");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIProjDescFieldEdit
        {
            get
            {
                if ((this.mUIProjDescFieldEdit == null))
                {
                    this.mUIProjDescFieldEdit = new WpfEdit(this);
                    #region Suchkriterien
                    this.mUIProjDescFieldEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "projDescField";
                    this.mUIProjDescFieldEdit.WindowTitles.Add("Neues Projekt erstellen.");
                    #endregion
                }
                return this.mUIProjDescFieldEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIProjDescFieldEdit;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UISpeichernunterWindow : WinWindow
    {
        
        public UISpeichernunterWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Speichern unter";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Speichern unter");
            #endregion
        }
        
        #region Properties
        public UIDetailbereichPane UIDetailbereichPane
        {
            get
            {
                if ((this.mUIDetailbereichPane == null))
                {
                    this.mUIDetailbereichPane = new UIDetailbereichPane(this);
                }
                return this.mUIDetailbereichPane;
            }
        }
        
        public UISpeichernWindow UISpeichernWindow
        {
            get
            {
                if ((this.mUISpeichernWindow == null))
                {
                    this.mUISpeichernWindow = new UISpeichernWindow(this);
                }
                return this.mUISpeichernWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDetailbereichPane mUIDetailbereichPane;
        
        private UISpeichernWindow mUISpeichernWindow;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIDetailbereichPane : WinPane
    {
        
        public UIDetailbereichPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinControl.PropertyNames.Name] = "Detailbereich";
            this.WindowTitles.Add("Speichern unter");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIDateinameComboBox
        {
            get
            {
                if ((this.mUIDateinameComboBox == null))
                {
                    this.mUIDateinameComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUIDateinameComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Dateiname:";
                    this.mUIDateinameComboBox.WindowTitles.Add("Speichern unter");
                    #endregion
                }
                return this.mUIDateinameComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIDateinameComboBox;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UISpeichernWindow : WinWindow
    {
        
        public UISpeichernWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Speichern unter");
            #endregion
        }
        
        #region Properties
        public WinButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUISpeichernButton.SearchProperties[WinButton.PropertyNames.Name] = "Speichern";
                    this.mUISpeichernButton.WindowTitles.Add("Speichern unter");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIÖffnenWindow : WinWindow
    {
        
        public UIÖffnenWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Öffnen";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Öffnen");
            #endregion
        }
        
        #region Properties
        public UIÖffnenTitleBar UIÖffnenTitleBar
        {
            get
            {
                if ((this.mUIÖffnenTitleBar == null))
                {
                    this.mUIÖffnenTitleBar = new UIÖffnenTitleBar(this);
                }
                return this.mUIÖffnenTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIÖffnenTitleBar mUIÖffnenTitleBar;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIÖffnenTitleBar : WinTitleBar
    {
        
        public UIÖffnenTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.WindowTitles.Add("Öffnen");
            #endregion
        }
        
        #region Properties
        public WinButton UISchließenButton
        {
            get
            {
                if ((this.mUISchließenButton == null))
                {
                    this.mUISchließenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUISchließenButton.SearchProperties[WinButton.PropertyNames.Name] = "Schließen";
                    this.mUISchließenButton.WindowTitles.Add("Öffnen");
                    #endregion
                }
                return this.mUISchließenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISchließenButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIProgramManagerWindow : WinWindow
    {
        
        public UIProgramManagerWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Program Manager";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Progman";
            this.WindowTitles.Add("Program Manager");
            #endregion
        }
        
        #region Properties
        public UIDesktopList UIDesktopList
        {
            get
            {
                if ((this.mUIDesktopList == null))
                {
                    this.mUIDesktopList = new UIDesktopList(this);
                }
                return this.mUIDesktopList;
            }
        }
        #endregion
        
        #region Fields
        private UIDesktopList mUIDesktopList;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "10.0.30319.1")]
    public class UIDesktopList : WinList
    {
        
        public UIDesktopList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinList.PropertyNames.Name] = "Desktop";
            this.WindowTitles.Add("Program Manager");
            #endregion
        }
        
        #region Properties
        public WinListItem UIOttooqatPrjListItem
        {
            get
            {
                if ((this.mUIOttooqatPrjListItem == null))
                {
                    this.mUIOttooqatPrjListItem = new WinListItem(this);
                    #region Suchkriterien
                    this.mUIOttooqatPrjListItem.SearchProperties[WinListItem.PropertyNames.Name] = "otto.oqatPrj";
                    this.mUIOttooqatPrjListItem.WindowTitles.Add("Program Manager");
                    #endregion
                }
                return this.mUIOttooqatPrjListItem;
            }
        }
        
        public WinListItem UITestoqatPrjListItem
        {
            get
            {
                if ((this.mUITestoqatPrjListItem == null))
                {
                    this.mUITestoqatPrjListItem = new WinListItem(this);
                    #region Suchkriterien
                    this.mUITestoqatPrjListItem.SearchProperties[WinListItem.PropertyNames.Name] = "test.oqatPrj";
                    this.mUITestoqatPrjListItem.WindowTitles.Add("Program Manager");
                    #endregion
                }
                return this.mUITestoqatPrjListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIOttooqatPrjListItem;
        
        private WinListItem mUITestoqatPrjListItem;
        #endregion
    }
}
