//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.Filter.NoiseGenerator
{
	using OqatInterface;
	using Plugins;
	using Plugins.Filter;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PF_NoiseGenerator : IPlugin, IFilterOqat, IFilterOqat
	{
		public virtual Bitmap process(object Bitmap frame)
		{
			throw new System.NotImplementedException();
		}

		public virtual void setParentControll(object Control parent)
		{
			throw new System.NotImplementedException();
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType><List<delegate>> getEventHandles()
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType><List<event>> getEvents()
		{
			throw new System.NotImplementedException();
		}

	}
}

