//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPlugin 
	{
		string namePlugin { get;set; }

		OptType OptType { get;set; }

		PluginManager PluginManager { get;set; }

		IEnumerable<IOptItem> IOptItem { get;set; }

		void getOptionsView();

		int getProgress();

	}
}

