//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OqatInterface
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using ViewModel;

	/// <remarks>vlcht wäre es praktisches das Teil als Klasse zu implementieren</remarks>
	public interface IVideoInfo 
	{
		string videoCodecName { get;set; }

		float [] frameMetricValue { get;set; }

		List<MacroEntrys> filteredBy { get;set; }

		string macroName { get;set; }

		List<Path> extraRessource { get;set; }

	}
}

