//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OqatInterface
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MacroEntry
	{
		private string pluginName
		{
			get;
			set;
		}

		private string mementoName
		{
			get;
			set;
		}

		private double startFrameRel
		{
			get;
			set;
		}

		private double endFrameRel
		{
			get;
			set;
		}

	}
}

