//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OqatInterface
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPlugin  : IMemorizable
	{
		string namePlugin { get;set; }

		PluginType type { get;set; }

		void setParentControll(object IAddChild parent);

		Dictionary<EventType><List<delegate>> getEventHandles();

		Dictionary<EventType><List<event>> getEvents();

	}
}

