//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OqatInterface
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IVideoHandler  : IPlugin
	{
		IVideoInfo vidInfo { get;set; }

		event videoConstructionDone { get;set; }

		Bitmap getFrame(object int frameNm);

		Bitmap[] getFrames(object int frameNm, object int offset);

		void writeFrame(object int frameNum, object Bitmap frame);

		void writeFrames(object int frameNum, object Bitmap[] frames);

	}
}

