//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ExtraResourceEventArgs : EventArgs
	{
		public virtual Path resourcepath
		{
			get;
			set;
		}

		public virtual PresentationPluginType resourcetype
		{
			get;
			set;
		}

	}
}

