//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel.Macro
{
	using OqatPublicRessources;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Macro : IMacro
	{
		public virtual List<MacroEntry> pluginList
		{
			get;
			set;
		}

		public virtual void setParentControll(object IAddChild parent)
		{
			throw new System.NotImplementedException();
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

		public virtual void onPluginlistEntrySelect(object object sender, object EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public virtual void createNewMemento(object List<string, object string mementoName)
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType,List<delegate>> getEventHandles()
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType,List<event>> getEvents()
		{
			throw new System.NotImplementedException();
		}

		public virtual List<MacroEntry> getPluginMementoList()
		{
			throw new System.NotImplementedException();
		}

	}
}

