//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel.Macro
{
	using OqatPublicRessources;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PF_MacroFilter : Macro, IFilterOqat
	{
		public virtual void setParentControll(object Control parent)
		{
			throw new System.NotImplementedException();
		}

		public override Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public override void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

		public virtual Bitmap process(object Bitmap frame)
		{
			throw new System.NotImplementedException();
		}

		public override Dictionary<EventType,List<delegate>> getEventHandles()
		{
			throw new System.NotImplementedException();
		}

		public override Dictionary<EventType,List<event>> getEvents()
		{
			throw new System.NotImplementedException();
		}

		public virtual void process(object Video vid, object Video vidResult)
		{
			throw new System.NotImplementedException();
		}

	}
}

