//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel.Macro
{
	using Plugins.Metric;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using ViewModel;

	public class VM_Macro
	{
		private ViewType viewType
		{
			get;
			set;
		}

		private Macro macro
		{
			get;
			set;
		}

		private Video vidRef
		{
			get;
			set;
		}

		private Video vidProc
		{
			get;
			set;
		}

		private Video vidResult
		{
			get;
			set;
		}

		public VM_Macro()
		{
		}

		private void onToggleView(object object sender, object EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void onStartProcess(object object sender, object EventArgs e))
		{
			throw new System.NotImplementedException();
		}

		private void onEntrySelect(object object sender, object MementoEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void onMacroSave(object object sender, object EventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

