//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AForge.Video
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IVideoSource 
	{
		Int64 BytesReceived { get; }

		int FramesReceived { get; }

		bool IsRunning { get; }

		string Source { get; }

		void SignalToStop();

		void Start();

		void Stop();

		void WaitForStop();

	}
}

