//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.YuvVideoHandler
{
	using OqatInterface;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PS_YuvVideoHandler : IVideoHandler
	{
		public virtual BitMap getFrame(object int frameNm)
		{
			throw new System.NotImplementedException();
		}

		public virtual BitMap[] getFrames(object int frameNm, object int offset)
		{
			throw new System.NotImplementedException();
		}

		public virtual void writeFrame(object int frameNum, object Bitmap frame)
		{
			throw new System.NotImplementedException();
		}

		public virtual void writeFrames(object int frameNum, object Bitmap[] frames)
		{
			throw new System.NotImplementedException();
		}

		public virtual void setParentControll(object Control parent)
		{
			throw new System.NotImplementedException();
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType><List<delegate>> getEventHandles()
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType><List<event>> getEvents()
		{
			throw new System.NotImplementedException();
		}

	}
}

