//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.OqatPresentation
{
	using AForge.Controls;
	using OqatPublicRessources;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PP_Player : IPresentation
	{
		public virtual IEnumerable<VideoSourcePlayer> VideoSourcePlayer
		{
			get;
			set;
		}

		public virtual VideoSource VideoSource
		{
			get;
			set;
		}

		public virtual void setParentControll(object IAddChild parent)
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType,List<delegate>> getEventHandles()
		{
			throw new System.NotImplementedException();
		}

		public virtual Dictionary<EventType,List<event>> getEvents()
		{
			throw new System.NotImplementedException();
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

		public virtual void loadVideo(object Video vid)
		{
			throw new System.NotImplementedException();
		}

		public virtual void unloadVideo()
		{
			throw new System.NotImplementedException();
		}

		public virtual void onFlushPresentationPlugins(object object sender, object EventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

