//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.OqatPresentation
{
	using AForge.Video;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VideoSource : IVideoSource
	{
		public virtual void SignalToStop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Start()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void WaitForStop()
		{
			throw new System.NotImplementedException();
		}

	}
}

