//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AForge.Controls
{
	using AForge.Video;
	using System;
	using System.Collections.Generic;
	using System.Drawing;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class VideoSourcePlayer : Control
	{
		public virtual bool AutoSizeControl
		{
			get;
			private set;
		}

		public virtual Color BorderColor
		{
			get;
			private set;
		}

		public virtual bool IsRunning
		{
			get;
			private set;
		}

		public virtual IVideoSource VideoSource
		{
			get;
			private set;
		}



		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		public VideoSourcePlayer()
		{
		}

		public virtual Bitmap GetCurrentVideoFrame()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SignalToStop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Start()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void WaitForStop()
		{
			throw new System.NotImplementedException();
		}

	}
}

