//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OqatPublicRessources.Model
{
	using Plugins.Metric;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VideoEventArgs : EventArgs
	{
		public virtual Video video
		{
			get;
			set;
		}

		public virtual bool isRefVid
		{
			get;
			set;
		}

	}
}

