//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.Presentation
{
	using Aforge;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PP_VideoSourcePlayer
	{
		public virtual IVideoSource VideoSource
		{
			get;
			set;
		}

		public virtual VM_Presentation VM_Presentation
		{
			get;
			set;
		}

	}
}

