//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.Presentation
{
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_Presentation : IPresentation
	{
		public virtual void getOptionsView()
		{
			throw new System.NotImplementedException();
		}

		public virtual int getProgress()
		{
			throw new System.NotImplementedException();
		}

	}
}

