//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>
	/// wir dürfen nicht vergessen, dass solche klassen für plugins zugänglich sein müssen sonst können Sie die Klasse ja nicht erstellen. Ist zwar einleuchtend aber genau deshalb sollte man aufpassen.
	/// 
	/// </remarks>
	public class MementoEventArgs : EventArgs
	{
		private string pluginKey
		{
			get;
			set;
		}

		private string mementoName
		{
			get;
			set;
		}

	}
}

