//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OqatApp
	{
		private VM_Oqat vm_Oqat
		{
			get;
			set;
		}

		private void initOqat()
		{
			throw new System.NotImplementedException();
		}

		public OqatApp()
		{
		}

		private void initPluginManager()
		{
			throw new System.NotImplementedException();
		}

	}
}

