//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_Macro
	{
		public VM_Macro()
		{
		}

		private void onToggleView(object object sender, object EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void onStartProcess(object object sender, object EventArgs e))
		{
			throw new System.NotImplementedException();
		}

		private void onEntrySelect(object object sender, object MementoEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void onMacroSave(object object sender, object EventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

