//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_Oqat
	{
		private VM_Welcome vM_Welcome
		{
			get;
			set;
		}

		private VM_PluginList vM_PluginList
		{
			get;
			set;
		}

		private object vM_ProjectExplorer
		{
			get;
			set;
		}

		private PluginManager pluginManager
		{
			get;
			set;
		}

		private ViewType currentView
		{
			get;
			set;
		}

		private delegate onToggleView
		{
			get;
			set;
		}

		private void initPluginLists()
		{
			throw new System.NotImplementedException();
		}

		private void initWelcome()
		{
			throw new System.NotImplementedException();
		}

		private void initProjectExplorer()
		{
			throw new System.NotImplementedException();
		}

		public VM_Oqat()
		{
		}

		private void initMenu()
		{
			throw new System.NotImplementedException();
		}

		private void initPresentation()
		{
			throw new System.NotImplementedException();
		}

		private void onBuildProjectView(object object sender, object eventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void onToggleView(object object sender, object EventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

