//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VM_ProjectExplorer
	{
		private TabControl projectExplorer
		{
			get;
			set;
		}

		private TreeView smartTree
		{
			get;
			set;
		}

		private TreeView fileExplorer
		{
			get;
			set;
		}

		private Project project
		{
			get;
			set;
		}

		private event videoClick
		{
			get;
			set;
		}

		private event videoLoad
		{
			get;
			set;
		}

		private PluginManager pluginManager
		{
			get;
			set;
		}

		private event fileSelect
		{
			get;
			set;
		}

		public VM_ProjectExplorer(object Project project, object Control parent)
		{
		}

	}
}

