//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Caretaker
	{
		private object caretaker Caretaker
		{
			get;
			set;
		}

		private Hashtable mementoTable
		{
			get;
			set;
		}

		public virtual Caretaker getCaretaker()
		{
			throw new System.NotImplementedException();
		}

		public virtual void remove(object string namePlugin, object string nameMemento)
		{
			throw new System.NotImplementedException();
		}

		public virtual void toDisk()
		{
			throw new System.NotImplementedException();
		}

		private Caretaker()
		{
		}

		public virtual void fromDisk(object Path mementoDir)
		{
			throw new System.NotImplementedException();
		}

		public virtual Entwurf::Model::Memento[] getMementos(object string origin)
		{
			throw new System.NotImplementedException();
		}

	}
}

