//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Memento
	{
		public virtual string name
		{
			get;
			set;
		}

		public virtual Object state
		{
			get;
			set;
		}

		public virtual IStorable IStorable
		{
			get;
			set;
		}

		public Memento(object String nameMemento, object Object state)
		{
		}

		public virtual Object getState()
		{
			throw new System.NotImplementedException();
		}

	}
}

