//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>
	/// check if vidName.mem exists:
	/// true -> Caretaker->loadPath->getMemento ->getState->.getCodecName -> check if Such VidHandler is installed -> addVideo to SmartTree
	/// </remarks>
	/// <remarks>Pathbasierte add methoden sollten raus, schließlich sind wir im model -> pathbasiert kann es sowieso nur ein handler machen</remarks>
	public class Project
	{
		private name string
		{
			get;
			set;
		}

		private description string
		{
			get;
			set;
		}

		private Path path_Project
		{
			get;
			set;
		}

		public virtual SmartNode<T> : where T: SmartNode SmartTree
		{
			get;
			set;
		}

		public Project(object string name, object Path path, object List<Video> vidList, object string description)
		{
		}

		public Project(object Path path)
		{
		}

		public Project(object string name, object Path path, object string description)
		{
		}

		public virtual void forcedVidRm(object Path vidPath)
		{
			throw new System.NotImplementedException();
		}

		public virtual void smoothVidRm(object Path vidPath)
		{
			throw new System.NotImplementedException();
		}

		public virtual void addVid(object Path vidPath)
		{
			throw new System.NotImplementedException();
		}

		public virtual void addVid(object Path vidPath, object Path vidPathFather)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Operation1()
		{
			throw new System.NotImplementedException();
		}

		public virtual void addVid(object Video vid)
		{
			throw new System.NotImplementedException();
		}

	}
}

