//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.Metric.MacroMetric
{
	using OqatInterface;
	using Plugins;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PF_MacroMetric : Macro, IMacro, IMetricOqat
	{
		public virtual void createNewMemento(object List<string[2]> plugMemList, object string mementoName)
		{
			throw new System.NotImplementedException();
		}

		public override List<MacroEntry> getPluginMementoList()
		{
			throw new System.NotImplementedException();
		}

		public override void setParentControll(object IAddChild parent)
		{
			throw new System.NotImplementedException();
		}

		public override Dictionary<EventType><List<delegate>> getEventHandles()
		{
			throw new System.NotImplementedException();
		}

		public override Dictionary<EventType><List<event>> getEvents()
		{
			throw new System.NotImplementedException();
		}

		public override Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public override void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

		public virtual IAnalysisInfo analyse(object Bitmap frame, object Bitmap frame)
		{
			throw new System.NotImplementedException();
		}

	}
}

