//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace View
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Windows;
	using System.Windows.Controls;
	using System.Windows.Markup;

	public class MainWindow : Window, IComponentConnector
	{
		private bool _contentLoaded;

		internal TreeView treeView1;

		internal TreeView treeView2;

		internal TreeView treeView3;

		internal TreeView treeView4;

		internal MenuItem Options;

		private void IComponentConnector.Connect(int connectionId, Object target)
		{
			throw new System.NotImplementedException();
		}

		public virtual void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		public MainWindow()
		{
		}

	}
}

