//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.CES_MotionVector
{
	using Plugins.OqatPresentation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PP_MotionVektor : PP_Player
	{
	}
}

