//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Plugins.Filter
{
	using AForge.Imaging;
	using Plugins;
	using Plugins.Metric;
	using System;
	using System.Collections.Generic;
	using System.Drawing;
	using System.Drawing.Imaging;
	using System.Linq;
	using System.Text;

	public class PF_Convolution : IPlugin, IFilterOqat
	{
		public virtual void getOptionsView()
		{
			throw new System.NotImplementedException();
		}

		public virtual int getProgress()
		{
			throw new System.NotImplementedException();
		}

		public virtual Video process(object Video ref)
		{
			throw new System.NotImplementedException();
		}

		public virtual Memento getMemento()
		{
			throw new System.NotImplementedException();
		}

		public virtual void setMemento(object Memento memento)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Apply(UnmanagedImage sourceImage, UnmanagedImage destinationImage)
		{
			throw new System.NotImplementedException();
		}

		public virtual UnmanagedImage Apply(UnmanagedImage image)
		{
			throw new System.NotImplementedException();
		}

		public virtual Bitmap Apply(Bitmap image)
		{
			throw new System.NotImplementedException();
		}

		public virtual Bitmap Apply(BitmapData imageData)
		{
			throw new System.NotImplementedException();
		}

	}
}

