//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Model;
using Plugins;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PluginManager
{
	private PluginManager pluginManager
	{
		get;
		set;
	}

	public virtual IEnumerable<IPlugin> IPlugin
	{
		get;
		set;
	}

	public virtual Caretaker : Collection<Memento> Caretaker
	{
		get;
		set;
	}

	public virtual IList<IPlugin> getPlugins(object OptType type)
	{
		throw new System.NotImplementedException();
	}

	public virtual static PluginManager getPluginManager()
	{
		throw new System.NotImplementedException();
	}

	private PluginManager()
	{
	}

	public virtual Memento getExtMemento(object string namePlugin, object string nameMemento)
	{
		throw new System.NotImplementedException();
	}

}

