//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using AForge.Video;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class YUVVideoSource : IVideoSource
{
	public virtual Int64 BytesReceived
	{
		get;
		private set;
	}

	public virtual int FramesReceived
	{
		get;
		private set;
	}

	public virtual bool IsRunning
	{
		get;
		private set;
	}

	public virtual string Source
	{
		get;
		private set;
	}




	public virtual void SignalToStop()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Stop()
	{
		throw new System.NotImplementedException();
	}

	public virtual void WaitForStop()
	{
		throw new System.NotImplementedException();
	}

	public YUVVideoSource()
	{
	}

}

